"""Add name field for social lInk

Revision ID: d2d8da871b14
Revises: ce88a4f77b8e
Create Date: 2025-03-12 16:54:52.442281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2d8da871b14'
down_revision: Union[str, None] = 'ce88a4f77b8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sociallinks', sa.Column('name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sociallinks', 'name')
    # ### end Alembic commands ###
