"""Add professions Table

Revision ID: 80cf8aa7d06f
Revises: 8503d3bd2ea2
Create Date: 2025-03-17 11:52:35.456122

"""
from typing import Sequence, Union

import fastapi_storages
from alembic import op
import sqlalchemy as sa
from src.models.profession import storage

# revision identifiers, used by Alembic.
revision: str = '80cf8aa7d06f'
down_revision: Union[str, None] = '8503d3bd2ea2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('professions',
                    sa.Column('name', sa.String(length=50), nullable=False),
                    sa.Column('description', sa.String(), nullable=True),
                    sa.Column('image', fastapi_storages.integrations.sqlalchemy.ImageType(storage), nullable=True),
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('is_published', sa.Boolean(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('professions')
    # ### end Alembic commands ###
