"""add reviewfield in Review

Revision ID: f686fbb851d5
Revises: 321ca019e22a
Create Date: 2025-03-15 12:35:01.593155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f686fbb851d5'
down_revision: Union[str, None] = '321ca019e22a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('review', sa.String(length=500), nullable=False))
    op.alter_column('reviews', 'profession',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reviews', 'profession',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    op.drop_column('reviews', 'review')
    # ### end Alembic commands ###
