"""Add section tables

Revision ID: 55e60eed8111
Revises: 9f096b96e9db
Create Date: 2025-03-17 12:50:48.774503

"""
from typing import Sequence, Union

import fastapi_storages
from alembic import op
import sqlalchemy as sa
from src.models.section import storage

# revision identifiers, used by Alembic.
revision: str = '55e60eed8111'
down_revision: Union[str, None] = '9f096b96e9db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sections',
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('title', sa.String(), nullable=False),
                    sa.Column('content', sa.String(), nullable=False),
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('is_published', sa.Boolean(), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('name')
                    )
    op.create_table('section_images',
                    sa.Column('image', fastapi_storages.integrations.sqlalchemy.ImageType(storage), nullable=False),
                    sa.Column('section_id', sa.UUID(), nullable=True),
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('is_published', sa.Boolean(), nullable=False),
                    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('section_images')
    op.drop_table('sections')
    # ### end Alembic commands ###
