"""add is_published field

Revision ID: 8503d3bd2ea2
Revises: f686fbb851d5
Create Date: 2025-03-16 20:58:29.364231

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '8503d3bd2ea2'
down_revision: Union[str, None] = 'f686fbb851d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('is_published', sa.Boolean(), nullable=False))
    op.add_column('reviews', sa.Column('is_published', sa.Boolean(), nullable=False))
    op.add_column('sociallinks', sa.Column('is_published', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sociallinks', 'is_published')
    op.drop_column('reviews', 'is_published')
    op.drop_column('contacts', 'is_published')
    # ### end Alembic commands ###
