"""change str length in client table

Revision ID: c966d5cfd20a
Revises: e78ed6c021ea
Create Date: 2025-04-05 15:27:36.395879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c966d5cfd20a'
down_revision: Union[str, None] = 'e78ed6c021ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('clients', 'phone',
               existing_type=sa.VARCHAR(length=12),
               type_=sa.String(length=13),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('clients', 'phone',
               existing_type=sa.String(length=13),
               type_=sa.VARCHAR(length=12),
               existing_nullable=False)
    # ### end Alembic commands ###
