"""add review model

Revision ID: 321ca019e22a
Revises: c5884c439dcd
Create Date: 2025-03-15 12:30:41.933803

"""
from typing import Sequence, Union

import fastapi_storages
from alembic import op
import sqlalchemy as sa
from src.models.review import storage


# revision identifiers, used by Alembic.
revision: str = '321ca019e22a'
down_revision: Union[str, None] = 'c5884c439dcd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reviews',
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('profession', sa.String(length=30), nullable=False),
                    sa.Column('image', fastapi_storages.integrations.sqlalchemy.ImageType(storage), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reviews')
    # ### end Alembic commands ###
