"""Add section tables delete unique

Revision ID: ec19355c9c76
Revises: 55e60eed8111
Create Date: 2025-03-17 13:21:06.026931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'ec19355c9c76'
down_revision: Union[str, None] = '55e60eed8111'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('sections_name_key', 'sections', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('sections_name_key', 'sections', ['name'])
    # ### end Alembic commands ###
