version: "3.9"
services:
  web:
    build: ./app
    volumes:
      - ./app:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
  db:
    image: postgres:14.8-alpine3.18
    environment:
      POSTGRES_DB: "db"
      POSTGRES_USER: "db"
      POSTGRES_PASSWORD: "db"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:

      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
 
volumes:
  db-data:
  

