version: "3.9"
services:
  db:
    image: postgres:14.8-alpine3.18
    volumes:
     - db-data:/var/lib/postgresql/data
    env_file:
      - .db.env
    ports:
      - "5432:5432"
  web:
    build: ./app
    volumes:
      - ./app/:/app/
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    command:  sh -c "alembic upgrade head && gunicorn --worker-class uvicorn.workers.UvicornWorker
               --workers $$(( 2 * $$(nproc) + 1 ))
               --bind 0.0.0.0:$${PORT}
               --timeout 120
               --keep-alive 5
               --access-logfile -
               --error-logfile -
               main:app"
  
 
volumes:
  db-data:
  

