FROM python:3.11-slim

WORKDIR /app

COPY req.txt .
RUN pip install --no-cache-dir -r req.txt

COPY . .

EXPOSE 8000

# Используем переменную окружения для указания пути к приложению


# CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]